version: "3.7"
services:
  service:
    build:
      context: ./service/artmaster
    links:
      - db
      - redis
      - celery
    environment:
      - CRAICBOX_DATABASE_PASSWORD=${CRAICBOX_DATABASE_PASSWORD}
      - CRAICBOX_DEBUG=1
      - CRAICBOX_HOST=0.0.0.0
      - CRAICBOX_URL=http://localhost:3000
      - SOCKETIO_PASSWORD=${SOCKETIO_PASSWORD}
    ports:
      - "5001:5001"
    volumes:
      - ./service/artmaster:/artmaster
  db:
    image: mysql:5
    command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${CRAICBOX_DATABASE_PASSWORD}
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
  # Redis - in-memory data store: https://redis.io/
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  # Celery - distributed background task runner: https://docs.celeryproject.org/en/stable/
  celery:
    build:
      context:
        ./service/artmaster
      dockerfile:
        celery.Dockerfile
    environment:
      - CRAICBOX_DATABASE_PASSWORD=${CRAICBOX_DATABASE_PASSWORD}
    volumes:
      - ./service/artmaster:/artmaster
    links:
      - redis
      - db
  ui:
    build:
      context: ./ui
    links:
      - service
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVICE_URL=http://localhost:5001
    volumes:
      - ./ui:/artmaster
  # Storybook - development environment for UI components: https://storybook.js.org/
  storybook:
    build:
      context: ./ui
    links:
      - service
    ports:
      - "9009:9009"
    volumes:
      - ./ui:/artmaster
    command:
      yarn run storybook
  seed:
    build:
      context:
        ./service/artmaster
      dockerfile:
        seed.Dockerfile
    environment:
      - CRAICBOX_DATABASE_PASSWORD=${CRAICBOX_DATABASE_PASSWORD}
    links:
      - db
  generate_data_model:
    build:
      context:
        ./service/artmaster
      dockerfile:
        generate_data_model.Dockerfile
    environment:
      - CRAICBOX_DATABASE_PASSWORD=${CRAICBOX_DATABASE_PASSWORD}
    volumes:
      - ./service/artmaster:/artmaster
    links:
      - db
  service_tests:
    build:
      context: ./service/artmaster
    links:
      - db
    working_dir: /artmaster
    volumes:
      - ./service/artmaster:/artmaster
    command:
      python -m unittest discover
