# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14

    working_directory: ~/repo/service/artmaster

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            cd service/artmaster
            pip install -r requirements.txt
        
      # run tests!
      - run:
          name: run tests
          command: |
            cd service/artmaster
            python -m unittest discover

      - store_artifacts:
          path: test-reports
          destination: test-reports