apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: celery
  namespace: craicbox
  labels:
    app: celery
spec:
  selector:
    matchLabels:
      app: celery
  replicas: 1
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: master
        image: rg.nl-ams.scw.cloud/craicbox/craicbox_celery
        env:
          - name: CRAICBOX_DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: mysql-root-password
          - name: NEW_RELIC_APP_NAME
            value: craicbox_celery
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                name: newrelic-secrets
                value: newrelic-password
          - name: NEW_RELIC_MONITOR_MODE
            value: true
        imagePullPolicy: Always
      imagePullSecrets:
        - name: regcred
