apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: craicbox
  namespace: craicbox
spec:
  secretName: certificate-craicbox
  renewBefore: 720h
  dnsNames:
  - craicbox.app
  - api.craicbox.app
  issuerRef:
    name: letsencrypt
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer