apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: craicbox
  labels:
    io.kompose.service: db-claim0
  name: db-claim0
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 10Gi
status: {}
