apiVersion: batch/v1
kind: Job
metadata:
  namespace: craicbox
  name: seed
spec:
  template:
    spec:
      containers:
      - image: rg.nl-ams.scw.cloud/craicbox/craicbox_seed:latest
        name: seed
        env:
        - name: CRAICBOX_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: CRAICBOX_HOST
          value: 0.0.0.0
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
