apiVersion: batch/v1
kind: Job
metadata:
  namespace: craicbox
  name: seed
spec:
  template:
    spec:
      containers:
      - image: rg.nl-ams.scw.cloud/craicbox/craicbox_seed:latest
        name: seed
      imagePullSecrets:
        - name: regcred
      restartPolicy: Never
