apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: service
  name: service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: service
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: service
    spec:
      containers:
      - image: art-master_service
        imagePullPolicy: Never
        name: service
        ports:
        - containerPort: 5001
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
status: {}
