CREATE TABLE User 
(
    UserId INT AUTO_INCREMENT NOT NULL, 
    Username VARCHAR(40) NOT NULL
)

CREATE TABLE Image
(
    ImageId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    UserId INT NOT NULL,
    Location VARCHAR(255) NOT NULL
)

ALTER TABLE Image
ADD FOREIGN KEY UserId
REFERENCES User(UserId)

CREATE TABLE Round
(
    RoundId INT AUTO_INCREMENT NOT NULL PRIMARY KEY
)

CREATE TABLE RoundImage
(
    RoundImageId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RoundId INT NOT NULL,
    ImageId INT NOT NULL
)

ALTER TABLE RoundImage
ADD FOREIGN KEY (RoundId)
REFERENCES Round(RoundId)

ALTER TABLE RoundImage
ADD FOREIGN KEY (ImageId)
REFERENCES Image(ImageId)

CREATE TABLE Rating 
(
    RatingId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    RaterUserId INT NOT NULL,
    RoundImageId INT NOT NULL,
    Rating INT NOT NULL
)

ALTER TABLE Rating
ADD FOREIGN KEY (RaterUserId)
REFERENCES User(UserId)

ALTER TABLE Rating
ADD FOREIGN KEY (RoundImageId)
REFERENCES RoundImage(RoundImageId)


