export const UPDATE_ROOM_STATE = "UPDATE_ROOM_STATE";
export const UPDATE_ROUND_STATE = "UPDATE_ROUND_STATE";
export const UPDATE_USER_STATE = "UPDATE_USER_STATE";
export const UPDATE_WORDS_STATE = "UPDATE_WORDS_STATE";
export const UPDATE_MINIGAMES_STATE = "UPDATE_MINIGAMES_STATE";